apiVersion: apps/v1
kind: Deployment
metadata:
  name: plain-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-plain
  template:
    metadata:
      labels:
        app: nginx-plain
    spec:
      containers:
        - name: nginx
          image: nginx:10.11
          ports:
            - containerPort: 80
