apiVersion: v1
kind: Service
metadata:
  name: plain-nginx-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
#      nodePort: 31000 # Sabit bir port veriyoruz
  selector:
    app: nginx-plain
